version: "3"

services:
  db:
    image: postgres
    container_name: db_service
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

volumes:
    db_data:
        driver: local
