"""Added Workflow, Node, NodeNode, StartNode, MessageNode, ConditionNode, EndNode

Revision ID: 82c8711a53ae
Revises: 
Create Date: 2024-04-24 15:18:19.059860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82c8711a53ae'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflows'))
    )
    op.create_table('nodes',
    sa.Column('type', sa.Enum('START', 'MESSAGE', 'CONDITION', 'END', name='nodetype'), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], name=op.f('fk_nodes_workflow_id_workflows'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nodes'))
    )
    op.create_table('condition_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('yes_node_id', sa.Integer(), nullable=True),
    sa.Column('no_node_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['nodes.id'], name=op.f('fk_condition_nodes_id_nodes')),
    sa.ForeignKeyConstraint(['no_node_id'], ['nodes.id'], name=op.f('fk_condition_nodes_no_node_id_nodes')),
    sa.ForeignKeyConstraint(['yes_node_id'], ['nodes.id'], name=op.f('fk_condition_nodes_yes_node_id_nodes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_condition_nodes'))
    )
    op.create_table('end_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['nodes.id'], name=op.f('fk_end_nodes_id_nodes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_end_nodes'))
    )
    op.create_table('message_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'OPENED', name='messagenodestatus'), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('next_node_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['nodes.id'], name=op.f('fk_message_nodes_id_nodes')),
    sa.ForeignKeyConstraint(['next_node_id'], ['nodes.id'], name=op.f('fk_message_nodes_next_node_id_nodes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_message_nodes'))
    )
    op.create_table('nodes_nodes',
    sa.Column('parent_node_id', sa.Integer(), nullable=False),
    sa.Column('child_node_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['child_node_id'], ['nodes.id'], name=op.f('fk_nodes_nodes_child_node_id_nodes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_node_id'], ['nodes.id'], name=op.f('fk_nodes_nodes_parent_node_id_nodes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('parent_node_id', 'child_node_id', name=op.f('pk_nodes_nodes'))
    )
    op.create_table('start_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('next_node_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['nodes.id'], name=op.f('fk_start_nodes_id_nodes')),
    sa.ForeignKeyConstraint(['next_node_id'], ['nodes.id'], name=op.f('fk_start_nodes_next_node_id_nodes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_start_nodes'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('start_nodes')
    op.drop_table('nodes_nodes')
    op.drop_table('message_nodes')
    op.drop_table('end_nodes')
    op.drop_table('condition_nodes')
    op.drop_table('nodes')
    op.drop_table('workflows')
    # ### end Alembic commands ###
