"""Added column condition to ConditionNode

Revision ID: e9b392d5b6d2
Revises: 82c8711a53ae
Create Date: 2024-04-25 10:46:50.057797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9b392d5b6d2'
down_revision: Union[str, None] = '82c8711a53ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('condition_nodes', sa.Column('condition', sa.Enum('STATUS_PENDING', 'STATUS_SENT', 'STATUS_OPENED', name='conditiononmessagestatus'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('condition_nodes', 'condition')
    # ### end Alembic commands ###
